from davisethernet.constants import bar_trend_map, forecast_icon_map

def LOOP(data):
    print('Current report:')
    print('    Bar trend:         {} ({})'.format(bar_trend_map[data['bar_trend']], data['bar_trend']))
    print('    Barometer:         {}'.format(data['barometer']))
    print('    Inside:')
    print('       Temperature:    {}'.format(data['inside_temp']))
    print('       Humidity:       {}'.format(data['inside_humid']))
    print('    Outside:')
    print('       Temperature:    {}'.format(data['outside_temp']))
    print('       Humidity:       {}'.format(data['outside_humid']))
    print('    Wind speed:')
    print('       Current:        {}'.format(data['wind_speed']))
    print('       Average:        {}'.format(data['avg_wind_speed']))
    print('    Wind direction:    {}'.format(data['wind_dir']))
    print('    Extra temps:       {}'.format(data['extra_temps']))
    print('    Soil temps:        {}'.format(data['soil_temps']))
    print('    Leaf temps:        {}'.format(data['leaf_temps']))
    print('    Extra humidity:    {}'.format(data['extra_humid']))
    print('    Rain rate:         {}'.format(data['rain_rate']))
    print('    UV:                {}'.format(data['uv']))
    print('    Solar radiation:   {}'.format(data['solar_rad']))
    print('    Storm rain:        {}'.format(data['storm_rain']))
    print('    Storm start:       {}'.format(data['storm_start']))
    print('    Day rain:          {}'.format(data['day_rain']))
    print('    Month rain:        {}'.format(data['month_rain']))
    print('    Year rain:         {}'.format(data['year_rain']))
    print('    Day ET:            {}'.format(data['day_ET']))
    print('    Month ET:          {}'.format(data['month_ET']))
    print('    Year ET:           {}'.format(data['year_ET']))
    print('    Soil moistures:    {}'.format(data['soil_moistures']))
    print('    Leaf wetness:      {}'.format(data['leaf_wetness']))
    print('    Inside alarms:     {}'.format(data['inside_alarms']))
    print('    Rain alarms:       {}'.format(data['rain_alarms']))
    print('    Outside alarms:    {}'.format(data['outside_alarms']))
    print('    Extra alarms:      {}'.format(data['extra_alarms']))
    print('    Soil alarms:       {}'.format(data['soil_alarms']))
    print('    TX Battery status: {}'.format(data['tx_batt_stat']))
    print('    Con Batt volts:    {}'.format(data['con_batt_volt']))
    print('    Forecast icons:    {} ({})'.format(forecast_icon_map[data['forecast_icons']], data['forecast_icons']))
    print('    Forecast rule:     {}'.format(data['forecast_rule']))
    print('    Sunrise:           {}'.format(data['sunrise']))
    print('    Sunset:            {}'.format(data['sunset']))

def LOOP2(data):
    print('Current report:')
    print('    Bar trend:         {} ({})'.format(bar_trend_map[data['bar_trend']], data['bar_trend']))
    print('    Barometer:         {}'.format(data['barometer']))
    print('    Inside:')
    print('       Temperature:    {}'.format(data['inside_temp']))
    print('       Humidity:       {}'.format(data['inside_humid']))
    print('    Outside:')
    print('       Temperature:    {}'.format(data['outside_temp']))
    print('       Humidity:       {}'.format(data['outside_humid']))
    print('    Wind:')
    print('       Speed:          {} @ {}'.format(data['wind_speed'], data['wind_dir']))
    print('       2-min average:  {}'.format(data['wind_spd_avg_2']))
    print('       10-min average: {}'.format(data['wind_spd_avg_10']))
    print('       10-min gust:    {} @ {}'.format(data['wind_gust_10'], data['wind_gust_10_dir']))
    print('    Dew point:         {}'.format(data['dew_point']))
    print('    Heat index:        {}'.format(data['heat_index']))
    print('    Wind chill:        {}'.format(data['wind_chill']))
    print('    THSW index:        {}'.format(data['THSW_index']))
    print('    Rain rate:         {}'.format(data['rain_rate']))
    print('    UV:                {}'.format(data['uv']))
    print('    Solar radiation:   {}'.format(data['solar_rad']))
    print('    Storm rain:        {}'.format(data['storm_rain']))
    print('    Storm start:       {}'.format(data['storm_start']))
    print('    Rain:')
    print('       Day:            {}'.format(data['rain_day']))
    print('       Last 15 min:    {}'.format(data['rain_last_15']))
    print('       Last 24 hr:     {}'.format(data['rain_last_hr']))
    print('    Day ET:            {}'.format(data['day_ET']))


def HILOWS(data):
    print('Barometer:')
    print('   Daily high: {} @ {}'.format(data['day_high_bar'], data['time_high_bar']))
    print('   Daily low:  {} @ {}'.format(data['day_low_bar'], data['time_low_bar']))
    print('   Month high: {}'.format(data['month_high_bar']))
    print('   Month low:  {}'.format(data['month_low_bar']))
    print('   Year high:  {}'.format(data['year_high_bar']))
    print('   Year low:   {}'.format(data['year_low_bar']))

    print('Wind speed:')
    print('   Daily high: {} @ {}'.format(data['day_high_wind'], data['time_high_wind']))
    print('   Month high: {}'.format(data['month_high_wind']))
    print('   Year high:  {}'.format(data['year_high_wind']))

    print('Inside temperature:')
    print('   Daily high: {} @ {}'.format(data['day_high_in_temp'], data['time_high_in_temp']))
    print('   Daily low:  {} @ {}'.format(data['day_low_in_temp'], data['time_low_in_temp']))
    print('   Month high: {}'.format(data['month_high_in_temp']))
    print('   Month low:  {}'.format(data['month_low_in_temp']))
    print('   Year high:  {}'.format(data['year_high_in_temp']))
    print('   Year low:   {}'.format(data['year_low_in_temp']))

    print('Inside humidity:')
    print('   Daily high: {} @ {}'.format(data['day_high_in_hum'], data['time_high_in_hum']))
    print('   Daily low:  {} @ {}'.format(data['day_low_in_hum'], data['time_low_in_hum']))
    print('   Month high: {}'.format(data['month_high_in_hum']))
    print('   Month low:  {}'.format(data['month_low_in_hum']))
    print('   Year high:  {}'.format(data['year_high_in_hum']))
    print('   Year low:   {}'.format(data['year_low_in_hum']))

    print('Outside temperature:')
    print('   Daily high: {} @ {}'.format(data['day_high_out_temp'], data['time_high_out_temp']))
    print('   Daily low:  {} @ {}'.format(data['day_low_out_temp'], data['time_low_out_temp']))
    print('   Month high: {}'.format(data['month_high_out_temp']))
    print('   Month low:  {}'.format(data['month_low_out_temp']))
    print('   Year high:  {}'.format(data['year_high_out_temp']))
    print('   Year low:   {}'.format(data['year_low_out_temp']))

    print('Dew point:')
    print('   Daily high: {} @ {}'.format(data['day_high_dew'], data['time_high_dew']))
    print('   Daily low:  {} @ {}'.format(data['day_low_dew'], data['time_low_dew']))
    print('   Month high: {}'.format(data['month_high_dew']))
    print('   Month low:  {}'.format(data['month_low_dew']))
    print('   Year high:  {}'.format(data['year_high_dew']))
    print('   Year low:   {}'.format(data['year_low_dew']))

    print('Wind chill:')
    print('   Daily low:  {} @ {}'.format(data['day_low_wchill'], data['time_low_wchill']))
    print('   Month low:  {}'.format(data['month_low_wchill']))
    print('   Year low:   {}'.format(data['year_low_wchill']))

    print('Heat index:')
    print('   Daily high:  {} @ {}'.format(data['day_high_heat'], data['time_high_heat']))
    print('   Month high:  {}'.format(data['month_high_heat']))
    print('   Year high:   {}'.format(data['year_high_heat']))

    print('THSW:')
    print('   Daily high:  {} @ {}'.format(data['day_high_THSW'], data['time_high_THSW']))
    print('   Month high:  {}'.format(data['month_high_THSW']))
    print('   Year high:   {}'.format(data['year_high_THSW']))

    print('Solar radiation:')
    print('   Daily high:  {} @ {}'.format(data['day_high_sol_rad'], data['time_high_sol_rad']))
    print('   Month high:  {}'.format(data['month_high_sol_rad']))
    print('   Year high:   {}'.format(data['year_high_sol_rad']))

    print('Rain rate:')
    print('   Daily high:  {} @ {}'.format(data['day_high_rain_rate'], data['time_high_rain_rate']))
    print('   Hour high:   {}'.format(data['hour_high_rain_rate']))
    print('   Month high:  {}'.format(data['month_high_rain_rate']))
    print('   Year high:   {}'.format(data['year_high_rain_rate']))
